medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "localhost"
      user: "postgres"
      password: "Blublah12@"
      port: 5432
      dbname: "medical_dw"
      schema: analytics
      threads: 4
