version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw telegram messages loaded from JSON data lake."
      - name: yolo_detections
        description: "Raw YOLO detections loaded from CSV."

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized Telegram messages for analytics."
    columns:
      - name: message_id
        description: "Unique message identifier from Telegram."
        tests: [unique, not_null]
      - name: channel_name
        description: "Telegram channel username/name."
        tests: [not_null]
      - name: message_ts
        description: "Message timestamp."
        tests: [not_null]
      
