version: 2

models:
  - name: dim_channels
    description: "Channel dimension."
    columns:
      - name: channel_key
        description: "Surrogate key for channel."
        tests: [unique, not_null]
      - name: channel_name
        tests: [unique, not_null]

  - name: dim_dates
    description: "Date dimension."
    columns:
      - name: date_key
        tests: [unique, not_null]
      - name: full_date
        tests: [unique, not_null]

  - name: fct_messages
    description: "Fact table for telegram messages."
    columns:
      - name: message_id
        tests: [unique, not_null]
      - name: channel_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
  - name: fct_image_detections
    description: "YOLO detections joined to messages for analysis."
    columns:
      - name: message_id
        tests: [not_null]
      - name: channel_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_key
      - name: date_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_dates')
                field: date_key
